version: "3.1"
services:
  social:
    container_name: social
    image: social
    build: .
    ports:
      - "${HTTP_PORT_EXTERNAL}:${HTTP_PORT_INTERNAL}"
    environment:
      HTTP_SERVER_ADDR: ${HTTP_SERVER_ADDR}
      DB_PRIMARY_CONNECTION: ${DB_PRIMARY_CONNECTION}
    depends_on:
      - social-db-0
    networks:
      - backend

  social-db-0:
    image: postgres:14.11-alpine3.18
    shm_size: 128mb
    ports:
      - "${DB_PRIMARY_EXTERNAL_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks:
      - backend
networks:
  backend:
